### ISSUE TITLE
BadRequest Exception on first install

### ISSUE THREAD

**Issue by seivad** [XeroAPI/xero-php-sample-app#6]
Just following your guide, fresh install and receive the following errors after creating a fresh public app and putting in the new consumer keys.

```
Notice: Object of class XeroPHP\Remote\Exception\BadRequestException could not be converted to int in /Users/mick/testing/xero-php-sample-app/src/app/Helper/CustomExceptionStrategy.php on line 27
```
```
Fatal error: Uncaught RuntimeException: Output has been emitted previously; cannot emit response in /Users/mick/testing/xero-php-sample-app/vendor/zendframework/zend-diactoros/src/Response/SapiEmitterTrait.php:31 Stack trace: #0 /Users/mick/testing/xero-php-sample-app/vendor/zendframework/zend-diactoros/src/Response/SapiEmitter.php(27): Zend\Diactoros\Response\SapiEmitter->assertNoPreviousOutput() #1 /Users/mick/testing/xero-php-sample-app/public/index.php(87): Zend\Diactoros\Response\SapiEmitter->emit(Object(Zend\Diactoros\Response)) #2 {main} thrown in /Users/mick/testing/xero-php-sample-app/vendor/zendframework/zend-diactoros/src/Response/SapiEmitterTrait.php on line 31
```

It's a shame the example doesn't work out of the box on a fresh install. Any ideas?

**Comment by seivad** [comment]
It was the callback URL, I didn't notice that it was required in the docs in this repo. 

Will close off. Also it would be worth having an example of the most important part of the SDK, creating invoices. I couldn't see any examples of that.

**Comment by Youdaman** [comment]
Running into the same issue. 

In the example config the callback url is set to `http://$_SERVER[HTTP_HOST]/application/callback`

What should it be? 

Apologies if this is obvious but I reckon the demo should work out of the box or have better instructions.

**Comment by Youdaman** [comment]
Actually I think I get it now after watching the Node demo via the docs: https://www.youtube.com/watch?v=SwyZctAmCu8

The errors occur on http://localhost:8999/application/connect because this `/application/connect` route/url is not implemented in this sample app, so I'm guessing I have to code my own callback endpoint similar to the Node demo.

Hopefully this of use to anyone else encountering this problem.

**Comment by Youdaman** [comment]
Looking again at the sample app code, that `/application/connect` route is defined in `src\app\Controller\ApplicationController.php`:

```
    public static function registerRoutes(RouteCollection $collection)
    {
        $controller = self::class;

        $collection->get('/', "$controller::index");
        $collection->group('application', function (RouteGroup $group) use ($controller) {

            $group->get('connect', "$controller::connect");
            $group->post('connect', "$controller::connectRedirect");
            $group->get('callback', "$controller::xeroCallback");
            $group->get('disconnect', "$controller::disconnect");
        });
    }
```

So maybe I'm missing something else.

**Comment by Youdaman** [comment]
Rather than get caught up with the routing of this app it turned out easier to get the basic public demo for xero-php working https://github.com/calcinai/xero-php/tree/master/examples

Just had to tweak the $config and add the consumer key/secret, change the callback url to `http://localhost:8000/public.php` and add a `require 'vendor/autoload.php';` after the `use` lines. Then run with `php -S localhost:8000` in the examples directory and visit http://localhost:8000/public.php
